// import "../css/style.css"
import "./components/Likes.js"
import "./components/SearchBox.js"
import "./components/Slider.js"
import "./components/MakeList.js"
import "./components/Head.js"
import "./components/Header.js"
import "./components/RevealSetions.js"
import "./components/BreadCrumbs.js"
import "./components/LightBox.js"
import "./components/Map.js"
