// import "../css/style.css"
import "./components/Head.js"
import "./components/BreadCrumbs.js"
import "./components/Constants.js"
import "./components/ContactForm7.js"
import "./components/Header.js"
import "./components/LightBox.js"
import "./components/Like.js"
import "./components/MakeList.js"
import "./components/Map.js"
import "./components/Product.js"
import "./components/RevealSetions.js"
import "./components/SearchBox.js"
import "./components/Slider.js"
import "./components/SortBtn.js"
